[package]
name = "racedet"
version.workspace = true
edition.workspace = true

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    ".",
    "example-crates/restapi",
    "example-crates/test-examples",
]

[features]
active = [
    "dep:futures-core",
    "dep:futures-executor",
    "dep:futures-util",
    "dep:itertools",
    "dep:pin-project-lite",
    "dep:rand",
]

[dependencies]
futures-core = { workspace = true, optional = true }
futures-executor = { workspace = true, optional = true, features = ["std"] }
futures-util = { workspace = true, optional = true, features = ["std"] }
itertools = { workspace = true, optional = true, features = ["use_std"] }
pin-project-lite = { workspace = true, optional = true }
rand = { workspace = true, optional = true, features = ["thread_rng"] }
# TODO: make tokio optional (it's a dependency of sync modules)
tokio = { workspace = true, features = ["sync", "rt", "time"] }
# TODO: make tracing optional (it's a dependency of sync modules)
tracing = { workspace = true }

[workspace.dependencies]
futures-core = { version = "0.3.31", default-features = false }
futures-executor = { version = "0.3.31", default-features = false }
futures-util = { version = "0.3.31", default-features = false }
itertools = { version = "0.14.0", default-features = false }
pin-project-lite = { version = "0.2.16", default-features = false }
racedet = { path = "." }
rand = { version = "0.9.2", default-features = false }
tokio = { version = "1.48.0", default-features = false }
tracing = { version = "0.1.41", default-features = false }
